trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*.*.*
  paths:
    include:
      - gateway-microservice/**
      - order-microservice/**
      - payment-microservice/**
      - product-microservice/**
      - store-ui/**
      - user-microservice/**

parameters:
  - name: manual_service
    displayName: 'Manual Deployment Target Option Override:'
    type: string
    default: 'automated_trigger'
    values:
      - automated_trigger
      - all
      - gateway-microservice
      - order-microservice
      - payment-microservice
      - product-microservice
      - store-ui
      - user-microservice

stages:
  - stage: GatewayLifecycle
    displayName: 'Gateway Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'gateway-microservice'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'gateway-microservice'

  - stage: OrderLifecycle
    displayName: 'Order Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'order-microservice'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'order-microservice'

  - stage: PaymentLifecycle
    displayName: 'Payment Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'payment-microservice'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'payment-microservice'

  - stage: ProductLifecycle
    displayName: 'Product Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'product-microservice'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'product-microservice'

  - stage: StoreUiLifecycle
    displayName: 'Store UI Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'store-ui'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'store-ui'

  - stage: UserLifecycle
    displayName: 'User Service Stream'
    condition: |
      or(
        eq('${{ parameters.manual_service }}', 'all'),
        eq('${{ parameters.manual_service }}', 'user-microservice'),
        and(eq('${{ parameters.manual_service }}', 'automated_trigger'), succeeded())
      )
    jobs:
      - template: templates/build-core.yml
        parameters:
          service_name: 'user-microservice'