parameters:
  - name: service_name
    type: string

jobs:
  - job: SecureBuildLifecycle
    displayName: 'Run Pipeline Sequence for ${{ parameters.service_name }}'
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
      - checkout: self
        fetchDepth: 0

      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'SonarQube_Service_Connection'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'SignalForge_${{ parameters.service_name }}'
          cliProjectName: 'SignalForge-${{ parameters.service_name }}'
          cliSources: '${{ parameters.service_name }}'

      - task: SonarQubeAnalyze@5

      - task: Docker@2
        displayName: 'Compile and Push Verified Cryptographic Image Layers'
        inputs:
          containerRegistry: 'SignalForge_ACR_Connection'
          repository: '${{ parameters.service_name }}'
          command: 'buildAndPush'
          Dockerfile: '${{ parameters.service_name }}/Dockerfile'
          buildContext: '.'
          tags: |
            build-$(Build.BuildId)